services:
  mongo1:
    image: ${MONGO_IMG_NAME}
    container_name: mongo1
    command: mongod --replSet mongo-replica-set --bind_ip localhost,mongo1
    ports:
      - 27017:27017
    networks:
      - mongoCluster
    volumes:
      - mongo1-data:/data/db
    env_file:
      - .env

  mongo2:
    image: ${MONGO_IMG_NAME}
    container_name: mongo2
    command: mongod --replSet mongo-replica-set --bind_ip localhost,mongo2
    ports:
      - 27018:27017
    networks:
      - mongoCluster
    volumes:
      - mongo2-data:/data/db


  mongo3:
    image: ${MONGO_IMG_NAME}
    container_name: mongo3
    command: mongod --replSet mongo-replica-set --bind_ip localhost,mongo3
    ports:
      - 27019:27017
    networks:
      - mongoCluster
    volumes:
      - mongo3-data:/data/db


  mongo-init:
    container_name: mongo-init
    image: ${MONGO_IMG_NAME}
    networks:
      - mongoCluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - /home/ubuntu/mongo_init:/docker-entrypoint-initdb.d
    restart: "no"
    entrypoint: [ "bash", "/docker-entrypoint-initdb.d/init.sh" ]

  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: polybot
    networks:
      - mongoCluster
      - yoloCluster
    ports:
      - 8443:8443
    depends_on:
      - mongo-init
      - my-yolo-app
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}


  my-yolo-app:
    image: ${YOLO5_IMG_NAME}
    container_name: my-yolo-app
    networks:
      - mongoCluster
      - yoloCluster
    ports:
      - 8081:8081
    depends_on:
      - mongo-init
    environment:
      - BUCKET_NAME=${BUCKET_NAME}

networks:
  mongoCluster:
  yoloCluster:
volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: